UmbracoNet/Models/Menu.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace UmbracoNet.Models
{

        public class MenuLink
        {
            public string Text { get; set; }
            public string Url { get; set; }


            public MenuLink() { }

            public MenuLink(string text, string url)
            {
                Text = text;
                Url = url;
            }
        }

        public class MenuList
        {
            public string Text { get; set; }
            public MenuLink Link { get; set; }

            public List<MenuList> Menus { get; set; }

            public MenuList(MenuLink link)
            {
                Link = link;
            }
        }

    
}

UmbracoNet/Models/Product.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web.Mvc;


namespace UmbracoNet.Models
{
    public class Product
    {

        public string category { get; set; }
        public string description { get; set; }
        public int id { get; set; }
        public string image { get; set; }
        public string name { get; set; }
    }

    public class Result
    {        public List<Product> products { get; set; }
    }

    public class RootObject
    {
        public Result result { get; set; }
        public bool ok { get; set; }
    }
}

UmbracoNet/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UmbracoNet.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

UmbracoNet/Controllers/ProductsController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.Web.Mvc;
using UmbracoNet.Models;

namespace UmbracoNet.Controllers
{
    public class ProductsController : SurfaceController
    {
        private const string ViewPath = "~/Views/Products/";


        public ActionResult RenderProductsView()
        {
            var url = "https://www.jsonstore.io/3f3b001398973ab65953b73e2da267bd9a7c5400483ff8a73c75c0e1fc76075c";
            var products = DownloadJsonData(url);

            if (products.ok)
            {
                var displayed = products.result.products.Where(product => product.category == "display");
                return PartialView(string.Format("{0}ProductsMainView.cshtml", ViewPath), displayed);
            }
            else
            {
                //manage error here
                return PartialView(string.Format("home.cshtml"));
            }
        }




        private static RootObject DownloadJsonData(string url)
        {
            using (var client = new WebClient())
            {
                var json = string.Empty;
                try
                {
                    json = client.DownloadString(url);
                }
                catch (Exception) {
                    RootObject objFalse = new RootObject { result = null, ok = false };
                    return objFalse;
                }


                RootObject obj = new JavaScriptSerializer().Deserialize<RootObject>(json);

                obj.result.products.Reverse();

                foreach (Product item in obj.result.products)
                {
                    item.description = ShortenDescription(item.description, 150);
                }
                return obj;
            }
        }


        public static string ShortenDescription(string input, int length)
        {
            if (input == null || input.Length < length)
                return input;
            int iNextSpace = input.LastIndexOf(" ", length, StringComparison.Ordinal);
            return string.Format("{0}…", input.Substring(0, (iNextSpace > 0) ? iNextSpace : length).Trim());
        }


    }
}

UmbracoNet/Controllers/SiteLayoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Umbraco.Web.Mvc;
using UmbracoNet.Models;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;

namespace UmbracoNet.Controllers
{
    public class SiteLayoutController : SurfaceController
    {
        private const string partialViewPath = "~/Views/Partials/Shared/";               

        public ActionResult RenderHeader()
        {
            var menu = GetMenus();

            return PartialView(string.Format("{0}Header.cshtml", partialViewPath), menu);
        }

        public ActionResult RenderFooter()
        {
            return PartialView(string.Format("{0}Footer.cshtml", partialViewPath));
        }
       


        public List<MenuList> GetMenus()
        {
            int id = int.Parse(CurrentPage.Path.Split(',')[1]); //position of page?
            IPublishedContent page = Umbraco.Content(id);

            var nav = new List<MenuList>
            {
                new MenuList(new MenuLink(page.Name, page.Url))
            };
            nav.AddRange(GetSubPages(page));

            return nav;
        }

        public List<MenuList> GetSubPages(dynamic page)
        {
            List<MenuList> menus = new List<MenuList>();

            var subPages = page.Children;

            foreach(var sub in subPages)
            {
                var item = new MenuList(new MenuLink(sub.Name, sub.Url));
                menus.Add(item);
            }

            return menus;
        }

    }
}

UmbracoNet/Views/Partials/Grid/Bootstrap3-Fluid.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@* 
    Razor helpers located at the bottom of this file
*@

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;
    
    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row);
                    }
                </div>
            }   
        }else { 
            <div class="row clearfix">
                @foreach (var s in Model.sections) {
                    <div class="grid-section">
                        <div class="col-md-@s.grid column">
                            @foreach (var row in s.rows) {
                                @renderRow(row);
                            }
                        </div>
                    </div>
                }
            </div>
        }
    </div>
}

@helper renderRow(dynamic row){
    <div @RenderElementAttributes(row)>
        <div class="row clearfix">
            @foreach ( var area in row.areas ) {
            <div class="col-md-@area.grid column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties())
            {
                var propertyValue = HttpUtility.HtmlAttributeEncode(property.Value.ToString());
                attrs.Add(property.Name + "=\"" + propertyValue + "\"");
            }

        JObject style = contentItem.styles;

        if (style != null) {
            var cssVals = new List<string>();
            foreach (JProperty property in style.Properties())
            {
                var propertyValue = property.Value.ToString();
                if (string.IsNullOrWhiteSpace(propertyValue) == false)
                {
                    cssVals.Add(property.Name + ":" + propertyValue + ";");
                }
            }

            if (cssVals.Any())
                attrs.Add("style='" + HttpUtility.HtmlAttributeEncode(string.Join(" ", cssVals)) + "'");
        }

        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

UmbracoNet/Views/Partials/Grid/Bootstrap3.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;

    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row, true);
                    }
                </div>
            }
        }else {
            <div class="container">
                <div class="row clearfix">
                    @foreach (var s in Model.sections) {
                        <div class="grid-section">
                            <div class="col-md-@s.grid column">
                                @foreach (var row in s.rows) {
                                    @renderRow(row, false);
                                }
                            </div>
                        </div>
                    }
                </div>
            </div>
        }
    </div>
}

@helper renderRow(dynamic row, bool singleColumn){
    <div @RenderElementAttributes(row)>
        @Html.If(singleColumn, "<div class='container'>")
        <div class="row clearfix">
            @foreach ( var area in row.areas ) {
            <div class="col-md-@area.grid column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
        @Html.If(singleColumn, "</div>")
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties())
            {
                var propertyValue = HttpUtility.HtmlAttributeEncode(property.Value.ToString());
                attrs.Add(property.Name + "=\"" + propertyValue + "\"");
            }

        JObject style = contentItem.styles;

        if (style != null) {
            var cssVals = new List<string>();
            foreach (JProperty property in style.Properties())
            {
                var propertyValue = property.Value.ToString();
                if (string.IsNullOrWhiteSpace(propertyValue) == false)
                {
                    cssVals.Add(property.Name + ":" + propertyValue + ";");
                }
            }

            if (cssVals.Any())
                attrs.Add("style=\"" + HttpUtility.HtmlAttributeEncode(string.Join(" ", cssVals)) + "\"");
        }

        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

UmbracoNet/Views/Partials/Grid/Editors/Base.cshtml
@model dynamic
@using Umbraco.Web.Templates

@functions {
    public static string EditorView(dynamic contentItem)
    {
        string view = contentItem.editor.render != null ? contentItem.editor.render.ToString() : contentItem.editor.view.ToString();
        view = view.ToLower().Replace(".html", ".cshtml");
        
        if (!view.Contains("/")) {
            view = "grid/editors/" + view;
        }

        return view;
    }
}
@try
{
    string editor = EditorView(Model);                                                       
    <text>@Html.Partial(editor, (object)Model)</text>
}
catch (Exception ex) { 
<pre>@ex.ToString()</pre>
}

UmbracoNet/Views/Partials/Grid/Editors/Embed.cshtml
@model dynamic
@using Umbraco.Web.Templates


<div class="video-wrapper">
	@Html.Raw(Model.value)
</div>

UmbracoNet/Views/Partials/Grid/Editors/Macro.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates


@if (Model.value != null)
{
    string macroAlias = Model.value.macroAlias.ToString();
    ViewDataDictionary parameters = new ViewDataDictionary();
    foreach (dynamic mpd in Model.value.macroParamsDictionary)
    {
        parameters.Add(mpd.Name, mpd.Value);
    }

    <text>
        @Umbraco.RenderMacro(macroAlias, parameters)
    </text>
}

UmbracoNet/Views/Partials/Grid/Editors/Media.cshtml
@model dynamic
@using Umbraco.Web.Templates

@if (Model.value != null)
{   
    var url = Model.value.image;
    if(Model.editor.config != null && Model.editor.config.size != null){
        url += "?width=" + Model.editor.config.size.width;
        url += "&height=" + Model.editor.config.size.height;

        if(Model.value.focalPoint != null){
            url += "&center=" + Model.value.focalPoint.top +"," + Model.value.focalPoint.left;
            url += "&mode=crop";
        }
    }

    var altText = Model.value.altText ?? Model.value.caption ?? string.Empty;
    
    <img src="@url" alt="@altText">
    
    if (Model.value.caption != null)
    {
        <p class="caption">@Model.value.caption</p>
    }
}

UmbracoNet/Views/Partials/Grid/Editors/Rte.cshtml
@model dynamic
@using Umbraco.Web.Composing
@using Umbraco.Web.Templates

@Html.Raw(TemplateUtilities.ParseInternalLinks(Model.value.ToString(), Current.UmbracoContext.UrlProvider))

UmbracoNet/Views/Partials/Grid/Editors/Textstring.cshtml
@model dynamic
@using Umbraco.Web.Composing
@using Umbraco.Web.Templates

@if (Model.editor.config.markup != null)
{
    string markup = Model.editor.config.markup.ToString();
    markup = markup.Replace("#value#", Html.ReplaceLineBreaksForHtml(HttpUtility.HtmlEncode((string)Model.value.ToString())).ToString());

    if (Model.editor.config.style != null)
    {
        markup = markup.Replace("#style#", Model.editor.config.style.ToString());
    }

    <text>
        @Html.Raw(markup)
    </text>
}
else
{
    <text>
        <div style="@Model.editor.config.style">@Model.value</div>
    </text>
}

UmbracoNet/Views/Partials/Shared/Footer.cshtml
@inherits UmbracoViewPage

<footer class="text-muted">
    <div class="container">
        <p class="float-right">
            <a href="#">Back to top</a>
        </p>
        <p>Umbraco</p>
        <p> @Umbraco.AssignedContentItem.Value("footerText")</p>
    </div>
</footer>

<!-- Load WP function in backend -->

UmbracoNet/Views/Partials/Shared/Header.cshtml
@using UmbracoNet.Models;
@using Umbraco.Web.Models;
@inherits Umbraco.Web.Mvc.UmbracoViewPage<List<MenuList>>


<header>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="/home">Umbraco Test</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                @RenderSubItems(Model)
                @helper RenderSubItems(List<MenuList> menuItems)
                {
                    foreach (var item in menuItems)
                    {
                        <li class="nav-item">
                            <a class="nav-link" href="@item.Link.Url">@item.Link.Text</a>
                        </li>
                    }
                }

                @*<li class="nav-item active">
                    <a class="nav-link" href="/home">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/products">Api</a>
                </li>*@
            </ul>
            <form class="form-inline mt-2 mt-md-0">
                <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
                <button class="btn btn-primary my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </nav>
</header>

UmbracoNet/Views/ProductDetail.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.ProductDetail>
@using ContentModels = Umbraco.Web.PublishedModels;
@{
	Layout = "base.cshtml";
}

UmbracoNet/Views/Products/ProductsMainView.cshtml
@using System.Web.Mvc
@using UmbracoNet.Models

@model IEnumerable<UmbracoNet.Models.Product>


<main role="main">

    <div class="container mt-5">
        <div class="row">
            <div class="col-12"><h1>Api calls in reverse</h1></div>
        </div>
    </div>


    <div class="album py-5 bg-light">
        <div class="container">

            <div class="row">

                @foreach (var item in Model)
                {
                    <div class="col-md-4">
                        <div class="card mb-4 shadow-sm">
                            <img class="bd-placeholder-img card-img-top" src="@Html.DisplayFor(modelItem => item.image)" alt="@Html.DisplayFor(modelItem => item.description)">
                            <div class="card-body">
                                <h3 class="card-title">
                                    @Html.DisplayFor(modelItem => item.name)
                                </h3>
                                <p class="card-text">
                                    
                                    @Html.DisplayFor(modelItem => item.description)
                                </p>
                            </div>
                        </div>
                    </div>
                }


            </div>

        </div>
    </div>

</main>

UmbracoNet/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

UmbracoNet/Views/base.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage
@{
    Layout = null;
}

@* the fun starts here *@

<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport">
    <meta content="" name="description">



    <link href="~/css/app.css" rel="stylesheet"></noscript>

    <!-- Load WP function in backend -->

    <script type="module" src="~/scripts/vendors.js" defer></script>
    <script type="module" src="~/scripts/app.js" defer></script>

    <script nomodule src="~/scripts/vendors-legacy.js" defer></script>
    <script nomodule src="~/scripts/app-legacy.js" defer></script>

</head>

<body>
   
    @{ Html.RenderAction("RenderHeader", "SiteLayout");}


    @RenderBody()
    


  


    @{ Html.RenderAction("RenderFooter", "SiteLayout");}
</body>

</html>

UmbracoNet/Views/home.cshtml
@inherits UmbracoViewPage
@using Umbraco.Web

@{
    Layout = "base.cshtml";
}

@* the fun starts here *@

<main role="main">

    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg"
                     preserveAspectRatio="xMidYMid slice" focusable="false" role="img">
                    <rect width="100%" height="100%" fill="#777" />
                </svg>
                <div class="container">
                    <div class="carousel-caption text-left">

                        <h1>@Umbraco.AssignedContentItem.Value("headlineOneTitle")</h1>
                        <p>
                            @Umbraco.AssignedContentItem.Value("headlineOne")
                        </p>
                        <p><a class="btn btn-lg btn-primary" href="@Umbraco.AssignedContentItem.Value("testButton")" role="button">Go To Products</a></p>
                    </div>
                </div>
            </div>
            <div class="carousel-item">
                <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg"
                     preserveAspectRatio="xMidYMid slice" focusable="false" role="img">
                    <rect width="100%" height="100%" fill="#777" />
                </svg>
                <div class="container">
                    <div class="carousel-caption">
                        <h1>@Umbraco.AssignedContentItem.Value("headlineTwoTitle")</h1>
                        <p>
                            @Umbraco.AssignedContentItem.Value("headlineTwoText")
                        </p>
                        <p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p>
                    </div>
                </div>
            </div>
            <div class="carousel-item">
                <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg"
                     preserveAspectRatio="xMidYMid slice" focusable="false" role="img">
                    <rect width="100%" height="100%" fill="#777" />
                </svg>
                <div class="container">
                    <div class="carousel-caption text-right">
                        <h1>@Umbraco.AssignedContentItem.Value("headlineThreeTitle")</h1>
                        <p>
                            @Umbraco.AssignedContentItem.Value("headlineThreeText")
                        </p>
                        <p><a class="btn btn-lg btn-primary" href="#" role="button">Browse gallery</a></p>
                    </div>
                </div>
            </div>
        </div>
        <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>

    <div class="container">
        <div class="row featurette">
            <div class="col-md-7 order-md-2">
                <h2 class="featurette-heading">@Umbraco.AssignedContentItem.Value("killerTitle")</h2>
                <p class="lead">@Umbraco.AssignedContentItem.Value("killerDescription")</p>
            </div>
            <div class="col-md-5 order-md-1">                
                <img class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" src="assets/images/186002.jpg">
            </div>
        </div>

        <hr class="featurette-divider">

        <div class="row featurette">
            <div class="col-md-7 ">
                <h2 class="featurette-heading">@Umbraco.AssignedContentItem.Value("thatGoodTitle")</h2>
                <p class="lead">@Umbraco.AssignedContentItem.Value("goodDescription")</p>
            </div>
            <div class="col-md-5 ">
                <img class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" src="assets/images/186002.jpg">
            </div>
        </div>

        <hr class="featurette-divider">

        <div class="row featurette">
            <div class="col-md-7 order-md-2">
                <h2 class="featurette-heading">@Umbraco.AssignedContentItem.Value("checkmateTitle")</h2>
                <p class="lead">@Umbraco.AssignedContentItem.Value("checkmateDescription")</p>
            </div>
            <div class="col-md-5 order-md-1">
                <img class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" src="assets/images/186002.jpg">
            </div>
        </div>


    </div>

</main>

UmbracoNet/Views/products.cshtml
@using UmbracoNet.Models
@{
    Layout = "base.cshtml";
}

@* the fun starts here *@


@{ Html.RenderAction("RenderProductsView", "Products");}